title: AI Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top NLP conference and workshop deadlines. This is fork of the original https://aideadlin.es/.

baseurl: ""
twitter_username: abhshkdz
github_username: abhshkdz

markdown: kramdown
ga_id: UA-36274081-2
